// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compile(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['Compile'](arg1, arg2, arg3);
}

export function Exit(arg1) {
  return window['go']['desktop']['App']['Exit'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['desktop']['App']['OpenProject'](arg1);
}
