// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bytes} from '../models';
import {url} from '../models';

export function Compile(arg1:bytes.Buffer):Promise<any>;

export function Transpile(arg1:bytes.Buffer):Promise<bytes.Buffer>;

export function TranspileFile(arg1:url.URL):Promise<bytes.Buffer>;
