// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateCode(arg1) {
  return window['go']['desktop']['App']['GenerateCode'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['desktop']['App']['OpenProject'](arg1);
}
