// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {project} from '../models';

export function Compile(arg1:Array<number>,arg2:Record<number, Array<number>>,arg3:string):Promise<void>;

export function Exit(arg1:context.Context):Promise<void>;

export function OpenProject(arg1:string):Promise<project.Project>;
