// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compile(arg1) {
  return window['go']['desktop']['App']['Compile'](arg1);
}

export function Transpile(arg1) {
  return window['go']['desktop']['App']['Transpile'](arg1);
}

export function TranspileFile(arg1) {
  return window['go']['desktop']['App']['TranspileFile'](arg1);
}
