// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';

export function GenerateCode(arg1:string):Promise<void>;

export function OpenProject(arg1:string):Promise<project.Project>;
