// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LookUp():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;
