// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ArrayType struct {
	_tab flatbuffers.Table
}

func GetRootAsArrayType(buf []byte, offset flatbuffers.UOffsetT) *ArrayType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ArrayType{}
	x.Init(buf, n+offset)
	return x
}

func FinishArrayTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsArrayType(buf []byte, offset flatbuffers.UOffsetT) *ArrayType {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ArrayType{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedArrayTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ArrayType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ArrayType) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ArrayType) Elem(obj *TypeDef) *TypeDef {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TypeDef)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ArrayType) Size() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ArrayType) MutateSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func ArrayTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ArrayTypeAddElem(builder *flatbuffers.Builder, elem flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(elem), 0)
}
func ArrayTypeAddSize(builder *flatbuffers.Builder, size uint64) {
	builder.PrependUint64Slot(1, size, 0)
}
func ArrayTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
