// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import "strconv"

type ChanDir byte

const (
	ChanDirBidirectional ChanDir = 0
	ChanDirSend          ChanDir = 1
	ChanDirReceive       ChanDir = 2
)

var EnumNamesChanDir = map[ChanDir]string{
	ChanDirBidirectional: "Bidirectional",
	ChanDirSend:          "Send",
	ChanDirReceive:       "Receive",
}

var EnumValuesChanDir = map[string]ChanDir{
	"Bidirectional": ChanDirBidirectional,
	"Send":          ChanDirSend,
	"Receive":       ChanDirReceive,
}

func (v ChanDir) String() string {
	if s, ok := EnumNamesChanDir[v]; ok {
		return s
	}
	return "ChanDir(" + strconv.FormatInt(int64(v), 10) + ")"
}
