// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import "strconv"

type Flag uint32

const (
	FlagNone      Flag = 0
	FlagNodeType1 Flag = 1
	FlagNodeType2 Flag = 2
	FlagNodeType3 Flag = 4
)

var EnumNamesFlag = map[Flag]string{
	FlagNone:      "None",
	FlagNodeType1: "NodeType1",
	FlagNodeType2: "NodeType2",
	FlagNodeType3: "NodeType3",
}

var EnumValuesFlag = map[string]Flag{
	"None":      FlagNone,
	"NodeType1": FlagNodeType1,
	"NodeType2": FlagNodeType2,
	"NodeType3": FlagNodeType3,
}

func (v Flag) String() string {
	if s, ok := EnumNamesFlag[v]; ok {
		return s
	}
	return "Flag(" + strconv.FormatInt(int64(v), 10) + ")"
}
