// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InterfaceType struct {
	_tab flatbuffers.Table
}

func GetRootAsInterfaceType(buf []byte, offset flatbuffers.UOffsetT) *InterfaceType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InterfaceType{}
	x.Init(buf, n+offset)
	return x
}

func FinishInterfaceTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInterfaceType(buf []byte, offset flatbuffers.UOffsetT) *InterfaceType {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InterfaceType{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInterfaceTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InterfaceType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InterfaceType) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InterfaceType) Methods(obj *InterfaceMethod, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *InterfaceType) MethodsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func InterfaceTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func InterfaceTypeAddMethods(builder *flatbuffers.Builder, methods flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(methods), 0)
}
func InterfaceTypeStartMethodsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func InterfaceTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
