// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InterfaceMethod struct {
	_tab flatbuffers.Table
}

func GetRootAsInterfaceMethod(buf []byte, offset flatbuffers.UOffsetT) *InterfaceMethod {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InterfaceMethod{}
	x.Init(buf, n+offset)
	return x
}

func FinishInterfaceMethodBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInterfaceMethod(buf []byte, offset flatbuffers.UOffsetT) *InterfaceMethod {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InterfaceMethod{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInterfaceMethodBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InterfaceMethod) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InterfaceMethod) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InterfaceMethod) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InterfaceMethod) FuncType() Type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Type(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *InterfaceMethod) MutateFuncType(n Type) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *InterfaceMethod) Func(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func InterfaceMethodStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func InterfaceMethodAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func InterfaceMethodAddFuncType(builder *flatbuffers.Builder, funcType Type) {
	builder.PrependByteSlot(1, byte(funcType), 0)
}
func InterfaceMethodAddFunc(builder *flatbuffers.Builder, func_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(func_), 0)
}
func InterfaceMethodEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
