// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import "strconv"

type NodeUnion byte

const (
	NodeUnionNONE        NodeUnion = 0
	NodeUnionIndexedNode NodeUnion = 1
	NodeUnionBinaryNode  NodeUnion = 2
	NodeUnionUnaryNode   NodeUnion = 3
)

var EnumNamesNodeUnion = map[NodeUnion]string{
	NodeUnionNONE:        "NONE",
	NodeUnionIndexedNode: "IndexedNode",
	NodeUnionBinaryNode:  "BinaryNode",
	NodeUnionUnaryNode:   "UnaryNode",
}

var EnumValuesNodeUnion = map[string]NodeUnion{
	"NONE":        NodeUnionNONE,
	"IndexedNode": NodeUnionIndexedNode,
	"BinaryNode":  NodeUnionBinaryNode,
	"UnaryNode":   NodeUnionUnaryNode,
}

func (v NodeUnion) String() string {
	if s, ok := EnumNamesNodeUnion[v]; ok {
		return s
	}
	return "NodeUnion(" + strconv.FormatInt(int64(v), 10) + ")"
}
