// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Node struct {
	_tab flatbuffers.Table
}

func GetRootAsNode(buf []byte, offset flatbuffers.UOffsetT) *Node {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Node{}
	x.Init(buf, n+offset)
	return x
}

func FinishNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNode(buf []byte, offset flatbuffers.UOffsetT) *Node {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Node{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Node) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Node) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Node) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Node) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *Node) Opcode() Opcode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Opcode(rcv._tab.GetUint32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Node) MutateOpcode(n Opcode) bool {
	return rcv._tab.MutateUint32Slot(6, uint32(n))
}

func (rcv *Node) Parent() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Node) MutateParent(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *Node) Next() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Node) MutateNext(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *Node) Flags() Flag {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return Flag(rcv._tab.GetUint32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Node) MutateFlags(n Flag) bool {
	return rcv._tab.MutateUint32Slot(12, uint32(n))
}

func (rcv *Node) NodeType() NodeUnion {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return NodeUnion(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Node) MutateNodeType(n NodeUnion) bool {
	return rcv._tab.MutateByteSlot(14, byte(n))
}

func (rcv *Node) Node(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func NodeStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func NodeAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(0, id, 0)
}
func NodeAddOpcode(builder *flatbuffers.Builder, opcode Opcode) {
	builder.PrependUint32Slot(1, uint32(opcode), 0)
}
func NodeAddParent(builder *flatbuffers.Builder, parent int64) {
	builder.PrependInt64Slot(2, parent, 0)
}
func NodeAddNext(builder *flatbuffers.Builder, next int64) {
	builder.PrependInt64Slot(3, next, 0)
}
func NodeAddFlags(builder *flatbuffers.Builder, flags Flag) {
	builder.PrependUint32Slot(4, uint32(flags), 0)
}
func NodeAddNodeType(builder *flatbuffers.Builder, nodeType NodeUnion) {
	builder.PrependByteSlot(5, byte(nodeType), 0)
}
func NodeAddNode(builder *flatbuffers.Builder, node flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(node), 0)
}
func NodeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
