// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PointerType struct {
	_tab flatbuffers.Table
}

func GetRootAsPointerType(buf []byte, offset flatbuffers.UOffsetT) *PointerType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PointerType{}
	x.Init(buf, n+offset)
	return x
}

func FinishPointerTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPointerType(buf []byte, offset flatbuffers.UOffsetT) *PointerType {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PointerType{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPointerTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PointerType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PointerType) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PointerType) ElemType() Type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Type(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PointerType) MutateElemType(n Type) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *PointerType) Elem(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func PointerTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PointerTypeAddElemType(builder *flatbuffers.Builder, elemType Type) {
	builder.PrependByteSlot(0, byte(elemType), 0)
}
func PointerTypeAddElem(builder *flatbuffers.Builder, elem flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(elem), 0)
}
func PointerTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
