// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TypeDef struct {
	_tab flatbuffers.Table
}

func GetRootAsTypeDef(buf []byte, offset flatbuffers.UOffsetT) *TypeDef {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TypeDef{}
	x.Init(buf, n+offset)
	return x
}

func FinishTypeDefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTypeDef(buf []byte, offset flatbuffers.UOffsetT) *TypeDef {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TypeDef{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTypeDefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TypeDef) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TypeDef) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TypeDef) Base() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TypeDef) MutateBase(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *TypeDef) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TypeDef) TypeType() Type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return Type(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TypeDef) MutateTypeType(n Type) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *TypeDef) Type(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func TypeDefStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func TypeDefAddBase(builder *flatbuffers.Builder, base uint32) {
	builder.PrependUint32Slot(0, base, 0)
}
func TypeDefAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(id), 0)
}
func TypeDefAddTypeType(builder *flatbuffers.Builder, typeType Type) {
	builder.PrependByteSlot(2, byte(typeType), 0)
}
func TypeDefAddType(builder *flatbuffers.Builder, type_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(type_), 0)
}
func TypeDefEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
