// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import "strconv"

type Type byte

const (
	TypeNONE          Type = 0
	TypePointerType   Type = 1
	TypeInterfaceType Type = 2
	TypeStructType    Type = 3
	TypeFuncType      Type = 4
	TypeMapType       Type = 5
	TypeArrayType     Type = 6
	TypeChanType      Type = 7
)

var EnumNamesType = map[Type]string{
	TypeNONE:          "NONE",
	TypePointerType:   "PointerType",
	TypeInterfaceType: "InterfaceType",
	TypeStructType:    "StructType",
	TypeFuncType:      "FuncType",
	TypeMapType:       "MapType",
	TypeArrayType:     "ArrayType",
	TypeChanType:      "ChanType",
}

var EnumValuesType = map[string]Type{
	"NONE":          TypeNONE,
	"PointerType":   TypePointerType,
	"InterfaceType": TypeInterfaceType,
	"StructType":    TypeStructType,
	"FuncType":      TypeFuncType,
	"MapType":       TypeMapType,
	"ArrayType":     TypeArrayType,
	"ChanType":      TypeChanType,
}

func (v Type) String() string {
	if s, ok := EnumNamesType[v]; ok {
		return s
	}
	return "Type(" + strconv.FormatInt(int64(v), 10) + ")"
}
