// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UnaryNode struct {
	_tab flatbuffers.Table
}

func GetRootAsUnaryNode(buf []byte, offset flatbuffers.UOffsetT) *UnaryNode {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UnaryNode{}
	x.Init(buf, n+offset)
	return x
}

func FinishUnaryNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUnaryNode(buf []byte, offset flatbuffers.UOffsetT) *UnaryNode {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UnaryNode{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUnaryNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UnaryNode) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UnaryNode) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UnaryNode) Value(obj *NodeValue) *NodeValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(NodeValue)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func UnaryNodeStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UnaryNodeAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func UnaryNodeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
