// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import "strconv"

type ValueFlag uint32

const (
	ValueFlagNone    ValueFlag = 0
	ValueFlagPointer ValueFlag = 1
)

var EnumNamesValueFlag = map[ValueFlag]string{
	ValueFlagNone:    "None",
	ValueFlagPointer: "Pointer",
}

var EnumValuesValueFlag = map[string]ValueFlag{
	"None":    ValueFlagNone,
	"Pointer": ValueFlagPointer,
}

func (v ValueFlag) String() string {
	if s, ok := EnumNamesValueFlag[v]; ok {
		return s
	}
	return "ValueFlag(" + strconv.FormatInt(int64(v), 10) + ")"
}
