// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tree

import "strconv"

type NodeUnion byte

const (
	NodeUnionNONE  NodeUnion = 0
	NodeUnionType1 NodeUnion = 1
	NodeUnionType2 NodeUnion = 2
	NodeUnionType3 NodeUnion = 3
)

var EnumNamesNodeUnion = map[NodeUnion]string{
	NodeUnionNONE:  "NONE",
	NodeUnionType1: "Type1",
	NodeUnionType2: "Type2",
	NodeUnionType3: "Type3",
}

var EnumValuesNodeUnion = map[string]NodeUnion{
	"NONE":  NodeUnionNONE,
	"Type1": NodeUnionType1,
	"Type2": NodeUnionType2,
	"Type3": NodeUnionType3,
}

func (v NodeUnion) String() string {
	if s, ok := EnumNamesNodeUnion[v]; ok {
		return s
	}
	return "NodeUnion(" + strconv.FormatInt(int64(v), 10) + ")"
}
