// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tree

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Type3 struct {
	_tab flatbuffers.Table
}

func GetRootAsType3(buf []byte, offset flatbuffers.UOffsetT) *Type3 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Type3{}
	x.Init(buf, n+offset)
	return x
}

func FinishType3Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsType3(buf []byte, offset flatbuffers.UOffsetT) *Type3 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Type3{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedType3Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Type3) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Type3) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Type3) Value(obj *NodeValue) *NodeValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(NodeValue)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func Type3Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func Type3AddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func Type3End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
