// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tree

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Type2 struct {
	_tab flatbuffers.Table
}

func GetRootAsType2(buf []byte, offset flatbuffers.UOffsetT) *Type2 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Type2{}
	x.Init(buf, n+offset)
	return x
}

func FinishType2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsType2(buf []byte, offset flatbuffers.UOffsetT) *Type2 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Type2{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedType2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Type2) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Type2) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Type2) Left(obj *NodeValue) *NodeValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(NodeValue)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Type2) Right(obj *NodeValue) *NodeValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(NodeValue)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func Type2Start(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func Type2AddLeft(builder *flatbuffers.Builder, left flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(left), 0)
}
func Type2AddRight(builder *flatbuffers.Builder, right flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(right), 0)
}
func Type2End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
